# Generated by Django 5.0.3 on 2024-03-26 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_note_is_hidden"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="note",
            name="unique_user_note",
        ),
    ]
