repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write", "./app/src/"]
        files: \.(vue|js|jsx|cjs|mjs|ts|tsx|cts|mts)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.49.0
    hooks:
      - id: eslint
        files: \.(vue|js|jsx|cjs|mjs|ts|tsx|cts|mts)$
        types: [file]
        args:
          [
            ".",
            "--ext",
            ".vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts",
            "--fix",
            "--ignore-path",
            ".gitignore",
          ]
        additional_dependencies:
          - eslint@8.49.0
          - "@rushstack/eslint-patch@1.3.3"
          - eslint-plugin-vue@9.17.0

  - repo: local
    hooks:
      - id: typescript
        files: ^app/
        language: system
        name: typescript
        entry: sh -c "cd app && npm run type-check"
        types_or: [ts, tsx, vue]
        pass_filenames: false
        require_serial: true
